version: '3.8'

services:
  web:
    build: ./app
    command: >
      sh -c "python manage.py flush --no-input &&
             python manage.py migrate &&
             python manage.py crawl &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sreality

volumes:
  postgres_data: